-- 1. JOBS 테이블에서 모든 컬럼을 조회하세요
SELECT
	*
FROM
	JOBS j; 

-- 2. LOCATIONS테이블에서  location_id, city 컬럼 조회
SELECT
	LOCATION_ID,
	CITY
FROM
	LOCATIONS l;

--3.  DEPARTMENTS 테이블에서 각 부서의 이름(DEPARTMENT_NAME)을 "부서명"이라는 별칭으로  조회하세요.
SELECT
	DEPARTMENT_NAME AS "부서명"
FROM
	DEPARTMENTS d;

--4. JOBS 테이블에서 중복 없이 모든 직무 유형(JOB_TITLE)을 조회하세요
SELECT
	DISTINCT JOB_TITLE
FROM
	JOBS j;

--5. EMPLOYEES 테이블에서 직원들의 이름+성을 Employee Name으로 조회하세요.
SELECT
	LAST_NAME || ' ' || FIRST_NAME AS "Employee Name"
FROM
	EMPLOYEES e;

--6. EMPLOYEES 테이블에서 급여가 5000 이상인 직원들의 정보(EMPLOYEE_ID, FIRST_NAME)
SELECT
	EMPLOYEE_ID,
	FIRST_NAME
FROM
	EMPLOYEES e
WHERE SALARY >= 5000;

--7. JOBS 테이블에서 최대 급여가 15000이상인 직무의 정보(JOB_ID, JOB_TITLE)을 조회하세요.
SELECT
	JOB_ID,
	JOB_TITLE
FROM
	JOBS j
WHERE
	MAX_SALARY >= 15000;

--8. EMPLOYEES 테이블에서 MANAGER_ID가 NULL이거나 JOB_ID가 HR_REP인 직원의 정보(EMPLOYE_ID, JOB_ID, COMMISSION_PCT)를 조회하세요.
SELECT
	EMPLOYEE_ID,
	JOB_ID,
	COMMISSION_PCT
FROM
	EMPLOYEES e
WHERE
	MANAGER_ID IS NULL
	OR JOB_ID = 'HR_REP';

--9. EMPLOYEES 테이블에서 보너스가 없는 직원들 조회하세요.
SELECT
	*
FROM
	EMPLOYEES e
WHERE
	COMMISSION_PCT IS NULL;

--10. EMPLOYEES 테이블에서 직무가 SA_REP 또는 PU_MAN인 직원들의 정보(NAME, PHONE, SALARY)를 조회하세요.
SELECT
	FIRST_NAME,
	LAST_NAME,
	PHONE_NUMBER,
	SALARY
FROM
	EMPLOYEES e
WHERE JOB_ID IN ('SA_REP', 'PU_MAN');
--WHERE JOB_ID = 'SA_REP' OR JOB_ID = 'PU_MAN';

--11. EMPLOYEES 테이블에서 JOB_ID가 SH로 시작하는 직원들의 정보(PHONE, JOB_ID, SALARY)를 조회하세요.
SELECT
	PHONE_NUMBER,
	JOB_ID,
	SALARY
FROM
	EMPLOYEES e
WHERE
	JOB_ID LIKE 'SH%';

--12. EMPLOYEES 테이블에서 FIRST_NAME이 4글자인 직원들의 정보(EMPLOYEE_ID, FIRST_NAME)을 조회하세요.
SELECT
	EMPLOYEE_ID,
	FIRST_NAME
FROM
	EMPLOYEES e
WHERE
	FIRST_NAME LIKE '____';

--13. LOCATIONS 테이블에서 CITY가 a로 끝나고, STATE_PROVINCE가 NULL인 데이터를 조회하세요.
SELECT
	*
FROM
	LOCATIONS l
WHERE
	CITY LIKE '%a'
	AND STATE_PROVINCE IS NULL;

--14. LOCATIONS 테이블에서 CITY와 STATE_PROVINCE가 동일한 데이터를 조회하세요.
SELECT
	*
FROM
	LOCATIONS l
WHERE
	CITY = STATE_PROVINCE;

--15. EMPLOYEES 테이블에서 보너스가 있는 직원들의 정보를 모두 출력하세요.
SELECT
	*
FROM
	EMPLOYEES e
WHERE
	COMMISSION_PCT IS NOT NULL;