--ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
--
--CREATE USER webadmin IDENTIFIED BY "qwer1234!";
--
--GRANT CONNECT, resource, dba TO webadmin;

GRANT CONNECT, resource, dba TO hr;

ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
ALTER USER hr IDENTIFIED BY "qwer1234!";

SELECT * FROM DEPARTMENTS d ;